name: Monthly ETL Workflow
on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at midnight on the first day of every month
  workflow_dispatch:
jobs:
  run-etl:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run ETL script
        run: ETL_MODE=QA python main.py

